export const LogoSBWep = '../../../public/Logo/LogoSBWep.png'
export const LogoSBW = '../../../public/Logo/SBW.png'
export const Facebook = '../../../public/icon/facebook.png'
export const Instagram  = '../../../public/icon/instagram.png'
export const Discord = '../../../public/icon/discord.png'
export const imgform = '../../../public/imgform.jpg'
export const default_profile = '../../../public/default_profile.png'
export const icon_instagram = '../../../public/icon/icon_instagram.png'
export const down_chevron = '../../../public/Use_icon/down_chevron.png'
export const more = '../../../public/Use_icon/more.png'
export const close = '../../../public/Use_icon/close.png'

